### ISSUE TITLE
Delete this repository

### ISSUE THREAD

**Issue by brmzkw** [scaleway/homebrew-scaleway#8]
If I make a PR to merge the docker-machine-driver-scaleway in homebrew, do you think this repository could be removed @moul @QuentinPerez ?

**Comment by moul** [comment]
yes

**Comment by brmzkw** [comment]
ok will do then, thanks :)

**Comment by bchatelard** [comment]
We also need to update the docker machine driver readme https://github.com/scaleway/docker-machine-driver-scaleway/blob/master/README.md#homebrew
